[package]
name = "fxr-reloader-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
dll-syringe = { workspace = true, features = ["rpc-payload", "payload-utils"]}
protocol = { workspace = true }
thiserror = { workspace = true }
