[package]
name = "fxr-reloader-agent"
version = "0.4.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dll-syringe = { workspace = true, features = ["rpc-payload", "payload-utils"]}
windows = { version = "0.48.0", features = ["Win32_System_LibraryLoader", "Win32_Foundation"] }
broadsword = { git = "https://github.com/vswarte/broadsword.git" }
protocol = { workspace = true }
pelite = "0.10"
